# Generated by Django 5.2.13 on 2026-04-29 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week", models.PositiveSmallIntegerField()),
                ("is_at_risk", models.BooleanField(default=False)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="students.enrollment",
                    ),
                ),
            ],
            options={
                "ordering": ("-week", "-evaluated_at"),
                "unique_together": {("enrollment", "week")},
            },
        ),
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_taken", models.TextField()),
                ("action_date", models.DateField()),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "risk_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="risk.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ("-action_date",),
            },
        ),
    ]
